version: '3.8'

services:
  backend:
    build: ./server
    container_name: expense-backend
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=postgresql://postgres:lpk123030@192.168.0.218:5432/expense_tracker
      - UPLOAD_DIR=/app/data/uploads
    restart: always

  frontend:
    build: ./expense-tracker
    container_name: expense-frontend
    ports:
      - "8090:8090"
    depends_on:
      - backend
    restart: always
